all:
  hosts:
    app1:
      ansible_host: 10.8.2.142
    database:
      ansible_host: 10.8.2.5
    traefik:
      ansible_host: 

wordpress_instances:
  hosts:
    app1:

database_instances:
  hosts:
    database:

proxy_instances:
  hosts:
    traefik:
